---
services:
  sonar_slack_bot:
    container_name: sonar-slack-bot
    # entrypoint: bun
    entrypoint: sh
    hostname: sonar_slack_bot
    restart: always
    build:
      context: .
      dockerfile: Containerfile
    # command: 'run bot.ts'
    command: 'entrypoint.sh'
    volumes:
      - .:/app:z
